In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "E:/icu_project/models/ui_backend_data_v2.csv"
)

df.head()

,predicted_probability,true_label,deterioration_24h,cardiovascular,respiratory,renal,neurologic,metabolic,alert,ai_summary,map_response_curve
0,0.028328,0.0,2.8,Normal,Normal,Stable,Normal,Stable,Stable,Patient stable. Continue routine monitoring.,"[60.0, 66.0729484625, 72.145896925, 78.2188453..."
1,0.713363,0.0,71.3,Critical,Critical,Failure Risk,Severe,Critical,Warning,Clinical deterioration likely. Physician revie...,"[60.0, 61.7914790625, 63.582958125, 65.3744371..."
2,0.018817,0.0,1.9,Normal,Normal,Stable,Normal,Stable,Stable,Patient stable. Continue routine monitoring.,"[60.0, 66.1323955625, 72.264791125, 78.3971866..."
3,0.225931,0.0,22.6,Normal,Normal,Stable,Normal,Stable,Stable,Patient stable. Continue routine monitoring.,"[60.0, 64.83792993750001, 69.675859875, 74.513..."
4,0.508967,0.0,50.9,Stress,Compromised,Monitor,Reduced,Stress,Warning,Clinical deterioration likely. Physician revie...,"[60.0, 63.068957499999996, 66.13791499999999, ..."

In [3]:
medications = [
    "Norepinephrine",
    "Epinephrine",
    "Propofol",
    "Fentanyl",
    "Midazolam",
    "Dobutamine",
    "Vasopressin"
]

In [4]:
def generate_medication_events(prob):

    events = []

    if prob > 0.7:
        events.append("Norepinephrine")

    if prob > 0.6:
        events.append("Vasopressin")

    if prob > 0.5:
        events.append("Propofol")

    if prob > 0.4:
        events.append("Fentanyl")

    if prob < 0.3:
        events.append("Midazolam")

    return events

In [5]:
df["medications"] = df["predicted_probability"].apply(
    generate_medication_events
)

df.head()

,predicted_probability,true_label,deterioration_24h,cardiovascular,respiratory,renal,neurologic,metabolic,alert,ai_summary,map_response_curve,medications
0,0.028328,0.0,2.8,Normal,Normal,Stable,Normal,Stable,Stable,Patient stable. Continue routine monitoring.,"[60.0, 66.0729484625, 72.145896925, 78.2188453...",[Midazolam]
1,0.713363,0.0,71.3,Critical,Critical,Failure Risk,Severe,Critical,Warning,Clinical deterioration likely. Physician revie...,"[60.0, 61.7914790625, 63.582958125, 65.3744371...","[Norepinephrine, Vasopressin, Propofol, Fentanyl]"
2,0.018817,0.0,1.9,Normal,Normal,Stable,Normal,Stable,Stable,Patient stable. Continue routine monitoring.,"[60.0, 66.1323955625, 72.264791125, 78.3971866...",[Midazolam]
3,0.225931,0.0,22.6,Normal,Normal,Stable,Normal,Stable,Stable,Patient stable. Continue routine monitoring.,"[60.0, 64.83792993750001, 69.675859875, 74.513...",[Midazolam]
4,0.508967,0.0,50.9,Stress,Compromised,Monitor,Reduced,Stress,Warning,Clinical deterioration likely. Physician revie...,"[60.0, 63.068957499999996, 66.13791499999999, ...","[Propofol, Fentanyl]"

In [6]:
timeline = [-4,-3,-2,-1,0]

def medication_timeline(prob):

    meds = generate_medication_events(prob)

    return {
        t: meds for t in timeline
    }

In [7]:
df["medication_timeline"] = df["predicted_probability"].apply(
    medication_timeline
)

In [8]:
df.to_csv(
    "E:/icu_project/models/ui_final_backend_dataset.csv",
    index=False
)